import { Calendar, Mic, Coffee, Users, Music, Award } from "lucide-react";
import { TimelineEvent } from "@/types/schedule";

export const timelineEvents: TimelineEvent[] = [
    {
      id: "1",
      time: "09:00",
      endTime: "09:45",
      title: "Registration & Check-in",
      description: "Come Register",
      location: "Main Entrance",
      type: "registration",
    },
    {
      id: "2",
      time: "10:00",
      endTime: "10:15",
      title: "Opening Remarks",
      description: "Welcome from the organizers",
      location: "Main Stage",
      type: "ceremony",
    },
    {
      id: "3",
      time: "10:15",
      endTime: "10:45",
      title: "Speaker 1",
      description: "-",
      location: "Main Stage",
      type: "talk",
    },
    {
      id: "4",
      time: "10:45",
      endTime: "11:15",
      title: "Coffee Break",
      description: "Networking",
      location: "Lobby",
      type: "break",
    },
    {
      id: "5",
      time: "11:15",
      endTime: "11:45",
      title: "Speaker 2",
      description: "-",
      location: "Main Stage",
      type: "talk",
    },
    {
      id: "6",
      time: "11:45",
      endTime: "12:30",
      title: "Workshop 1",
      description: "-",
      location: "Room A",
      type: "workshop",
    },
    {
      id: "7",
      time: "12:30",
      endTime: "13:30",
      title: "Lunch Break",
      description: "Catered lunch",
      location: "Room B",
      type: "break",
    },
    {
      id: "8",
      time: "13:30",
      endTime: "14:00",
      title: "Speaker 3",
      description: "-",
      location: "Main Stage",
      type: "talk",
    },
    {
      id: "9",
      time: "14:00",
      endTime: "14:30",
      title: "Speaker 4",
      description: "- ",
      location: "Main Stage",
      type: "talk",
    },
    {
      id: "10",
      time: "14:30",
      endTime: "15:00",
      title: "Speaker 5",
      description: "-",
      location: "Main Stage",
      type: "talk",
    },
    {
      id: "11",
      time: "15:00",
      endTime: "15:30",
      title: "Closing Ceremony",
      description: "Final remarks",
      location: "Main Stage",
      type: "ceremony",
    },
  ];

export const eventIcons: Record<TimelineEvent["type"], React.ComponentType<{ className?: string }>> = {
  registration: Calendar,
  talk: Mic,
  break: Coffee,
  workshop: Users,
  performance: Music,
  ceremony: Award,
};

export const eventColors: Record<TimelineEvent["type"], string> = {
  registration: "bg-neutral-100 text-neutral-600",
  talk: "bg-amber-50 text-amber-600",
  break: "bg-emerald-50 text-emerald-600",
  workshop: "bg-violet-50 text-violet-600",
  performance: "bg-pink-50 text-pink-600",
  ceremony: "bg-sky-50 text-sky-600",
};

export const dotColors: Record<TimelineEvent["type"], string> = {
  registration: "bg-neutral-400",
  talk: "bg-amber-400",
  break: "bg-emerald-400",
  workshop: "bg-violet-400",
  performance: "bg-pink-400",
  ceremony: "bg-sky-400",
};